plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - cryptography-and-security.md
  - README.md
  - Decentralized-Systems-Engineering.md
  - "Foundations of Software.md"
  - Information-security-and-privacy.md
  - TCP-IP-Networking.md
  - Understanding-Modern-Switzerland.md
